language: php
dist: trusty
sudo: required
php:
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'
install:
  - if [[ $TRAVIS_PHP_VERSION = '7.1' ]]; then wget -O ~/.phpenv/versions/$(phpenv version-name)/bin/phpunit https://phar.phpunit.de/phpunit-7.phar; fi
  - if [[ $TRAVIS_PHP_VERSION = '7.2' ]]; then wget -O ~/.phpenv/versions/$(phpenv version-name)/bin/phpunit https://phar.phpunit.de/phpunit-8.phar; fi
before_script:
  - composer install
script:
  - php -v
  - phpunit --version
  - phpunit tests --coverage-text --whitelist src\WidgetsProvider.php
after_success:
  - bash <(curl -s https://codecov.io/bash)
