language: php
dist: trusty
sudo: required
php:
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'
before_script:
  - composer install
script:
  - php -v
  - phpunit --version
after_success:
  - bash <(curl -s https://codecov.io/bash)
